# `repo` expects a GitHub repo.
repo: https://github.com/myplanetdigital/myplanet.git
branch: develop

# For timestamps in Jenkins UI
timezone: America/Toronto

# Only the entries below in the `users` database will be acted on.
# Each user created will be given passwordless sudo access.
# Example: [user1, user2]
users: [patcon]

github:
  organization: myplanetdigital
  # In order to use GitHub authentication, you'll need to register an app
  # See: https://github.com/settings/applications
  # Leaving these blank will use Jenkins database for authentication.
  # (Do not try GitHub authentication on Vagrant as it will break Jenkins.)
  client_id:
  secret:
